[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    bblanchon/ArduinoJson@^6.21.3

build_flags = 
    -D ARDUINOJSON_USE_LONG_LONG=1
    -D CORE_DEBUG_LEVEL=3

board_build.partitions = partitions.csv
