apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: blockchain-monitor
      defaultBucket: node-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: secret-token
    isDefault: true
    editable: true
