# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tracefault_pb2 as tracefault__pb2


class TraceFaultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryTrace = channel.unary_unary(
                '/tracefault.TraceFaultService/QueryTrace',
                request_serializer=tracefault__pb2.TraceRequest.SerializeToString,
                response_deserializer=tracefault__pb2.TraceResponse.FromString,
                )
        self.WatchFaults = channel.unary_unary(
                '/tracefault.TraceFaultService/WatchFaults',
                request_serializer=tracefault__pb2.WatchRequest.SerializeToString,
                response_deserializer=tracefault__pb2.WatchResponse.FromString,
                )


class TraceFaultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchFaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraceFaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTrace,
                    request_deserializer=tracefault__pb2.TraceRequest.FromString,
                    response_serializer=tracefault__pb2.TraceResponse.SerializeToString,
            ),
            'WatchFaults': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchFaults,
                    request_deserializer=tracefault__pb2.WatchRequest.FromString,
                    response_serializer=tracefault__pb2.WatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracefault.TraceFaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TraceFaultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracefault.TraceFaultService/QueryTrace',
            tracefault__pb2.TraceRequest.SerializeToString,
            tracefault__pb2.TraceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchFaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracefault.TraceFaultService/WatchFaults',
            tracefault__pb2.WatchRequest.SerializeToString,
            tracefault__pb2.WatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
